export interface Project {
  id: number
  projectNumber: number | string
  province: string
  municipality: string
  closestSe: string
  seAvailablePower: number | string
  mvlSeDistance: number | string
  usableSurface: number | string
  sellingPrice: string
  unitPrice: string
  rentingPrice: number | string
  pvPower: number | string
  bessPower: number | string
  landContractStatus: string
  peakPower: number | string
  accessCapacity: number | string
  technology: string
  production: number | string
  administrativeStatus: string
  rtbEstimation: string
  codEstimation: string
}

export const projectsData: Project[] = [
  {
    id: 1,
    projectNumber: 1,
    province: 'Barcelona',
    municipality: 'Granollers',
    closestSe: 'LA ROCA',
    seAvailablePower: 138.1,
    mvlSeDistance: 30,
    usableSurface: 5.50,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 1500,
    pvPower: 4.00,
    bessPower: 8.00,
    landContractStatus: 'Contract signed',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 2,
    projectNumber: 2,
    province: 'Barcelona',
    municipality: 'La Roca del vallés',
    closestSe: 'LA ROCA',
    seAvailablePower: 138.1,
    mvlSeDistance: 270,
    usableSurface: 9.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2000,
    pvPower: 4.00,
    bessPower: 8.00,
    landContractStatus: 'Contract signed',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 3,
    projectNumber: 3,
    province: 'Gerona',
    municipality: 'Vilademuns',
    closestSe: 'JUIA',
    seAvailablePower: 'NA',
    mvlSeDistance: 400,
    usableSurface: 7.50,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2700,
    pvPower: 3.20,
    bessPower: 8.00,
    landContractStatus: 'Contract signed',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 4,
    projectNumber: 4,
    province: 'Gerona',
    municipality: 'Holtalric',
    closestSe: 'BUIXALLEU',
    seAvailablePower: 27.7,
    mvlSeDistance: 'Inside',
    usableSurface: 7.70,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2393,
    pvPower: 4.00,
    bessPower: 8.00,
    landContractStatus: 'Negotiated. Under Legal revisión',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 5,
    projectNumber: 5,
    province: 'Barcelona',
    municipality: 'Llinars del valles',
    closestSe: 'LLINARS',
    seAvailablePower: 95,
    mvlSeDistance: 'Inside',
    usableSurface: 7.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2393,
    pvPower: 3.20,
    bessPower: 8.00,
    landContractStatus: 'Negotiated. Under Legal revisión',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 6,
    projectNumber: 6,
    province: 'Barcelona',
    municipality: 'Puigreig',
    closestSe: 'SALLENT',
    seAvailablePower: 20.4,
    mvlSeDistance: 'Inside',
    usableSurface: 8.50,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2000,
    pvPower: 4.00,
    bessPower: 8.00,
    landContractStatus: 'Under negotiation',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 7,
    projectNumber: 7,
    province: 'Barcelona',
    municipality: 'La llacuna',
    closestSe: 'ANOIA',
    seAvailablePower: 21.4,
    mvlSeDistance: 0,
    usableSurface: 12.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 4.00,
    bessPower: 8.00,
    landContractStatus: 'Under negotiation',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 8,
    projectNumber: 8,
    province: 'Barcelona',
    municipality: 'Avinyonet del Penedés',
    closestSe: 'MOJA',
    seAvailablePower: 93.7,
    mvlSeDistance: 50,
    usableSurface: 8.90,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 4.00,
    bessPower: 8.00,
    landContractStatus: 'Under negotiation',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 9,
    projectNumber: 9,
    province: 'Barcelona',
    municipality: 'Torrella del Foix',
    closestSe: 'MOJA',
    seAvailablePower: 93.7,
    mvlSeDistance: 50,
    usableSurface: 8.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 4.00,
    bessPower: 8.00,
    landContractStatus: 'Under negotiation',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 10,
    projectNumber: 10,
    province: 'Barcelona',
    municipality: 'San frutuos del Bages',
    closestSe: 'MANRESA',
    seAvailablePower: 41.7,
    mvlSeDistance: 2.4,
    usableSurface: 8.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 4.00,
    bessPower: 8.00,
    landContractStatus: 'Under negotiation',
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    administrativeStatus: 'NA',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 11,
    projectNumber: 'NA',
    province: 'Girona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    landContractStatus: 'NA',
    peakPower: 2.06,
    accessCapacity: 1.7,
    technology: 'Fija',
    production: 3329,
    administrativeStatus: 'Obtenida AE Definitiva. En operación',
    rtbEstimation: '-',
    codEstimation: 'sep-25'
  },
  {
    id: 12,
    projectNumber: 'NA',
    province: 'Lleida',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    landContractStatus: 'NA',
    peakPower: 3.28,
    accessCapacity: 2.75,
    technology: 'Fija',
    production: 5304,
    administrativeStatus: 'Obtenida AE Provisional.',
    rtbEstimation: '-',
    codEstimation: 'nov-25'
  },
  {
    id: 13,
    projectNumber: 'NA',
    province: 'Teruel',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    landContractStatus: 'NA',
    peakPower: 2,
    accessCapacity: 1.6,
    technology: 'Tracker',
    production: 3914,
    administrativeStatus: 'Solicitada licencia de obras',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 14,
    projectNumber: 'NA',
    province: 'Barcelona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    landContractStatus: 'NA',
    peakPower: 2.2,
    accessCapacity: 1.8,
    technology: 'Tracker',
    production: 3966,
    administrativeStatus: 'Pendiente solicitar licencia de obras',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 15,
    projectNumber: 'NA',
    province: 'Barcelona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    landContractStatus: 'NA',
    peakPower: 2.5,
    accessCapacity: 2,
    technology: 'Fija',
    production: 3966,
    administrativeStatus: 'Solicitada licencia de obras',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 16,
    projectNumber: 'NA',
    province: 'Barcelona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    landContractStatus: 'NA',
    peakPower: 2.4,
    accessCapacity: 2,
    technology: 'Fija',
    production: 3856,
    administrativeStatus: 'Obtenida licencia de obras',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 17,
    projectNumber: 'NA',
    province: 'Zaragoza',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    landContractStatus: 'NA',
    peakPower: 30,
    accessCapacity: 25,
    technology: 'Tracker',
    production: 58606,
    administrativeStatus: 'Obtenida licencia de obras',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 18,
    projectNumber: 'NA',
    province: 'Barcelona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    landContractStatus: 'NA',
    peakPower: 3.1,
    accessCapacity: 2.75,
    technology: 'Fija',
    production: 4805,
    administrativeStatus: 'Obtenida licencia de obras',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  }
]
