export interface Project {
  id: number
  projectNumber: number | string
  province: string
  municipality: string
  closestSe: string
  seAvailablePower: number | string
  mvlSeDistance: number | string
  usableSurface: number | string
  sellingPrice: string
  unitPrice: string
  rentingPrice: number | string
  pvPower: number | string
  bessPower: number | string
  peakPower: number | string
  accessCapacity: number | string
  technology: string
  production: number | string
  projectStatus: string
  rtbEstimation: string
  codEstimation: string
}

export const projectsData: Project[] = [
  {
    id: 1,
    projectNumber: '017FCAT25',
    province: 'Barcelona',
    municipality: 'Granollers',
    closestSe: 'LA ROCA',
    seAvailablePower: 138.1,
    mvlSeDistance: 30,
    usableSurface: 5.50,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 1500,
    pvPower: 4.00,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Contract Signed',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 2,
    projectNumber: '013FCAT25',
    province: 'Barcelona',
    municipality: 'La Roca del vallés',
    closestSe: 'LA ROCA',
    seAvailablePower: 138.1,
    mvlSeDistance: 270,
    usableSurface: 9.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2000,
    pvPower: 4.00,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Contract Signed',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 3,
    projectNumber: '008FCAT25',
    province: 'Gerona',
    municipality: 'Vilademuns',
    closestSe: 'JUIA',
    seAvailablePower: 'NA',
    mvlSeDistance: 400,
    usableSurface: 7.50,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2700,
    pvPower: 3.20,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Contract Signed',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 4,
    projectNumber: '022FCAT25',
    province: 'Gerona',
    municipality: 'Holtalric',
    closestSe: 'BUIXALLEU',
    seAvailablePower: 27.7,
    mvlSeDistance: 'Inside',
    usableSurface: 7.70,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2393,
    pvPower: 4.00,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Negotiated - Under Legal Review',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 5,
    projectNumber: '027FCAT25',
    province: 'Barcelona',
    municipality: 'Llinars del valles',
    closestSe: 'LLINARS',
    seAvailablePower: 95,
    mvlSeDistance: 'Inside',
    usableSurface: 7.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2393,
    pvPower: 3.20,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Negotiated - Under Legal Review',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 6,
    projectNumber: '023FCAT25',
    province: 'Barcelona',
    municipality: 'Puigreig',
    closestSe: 'SALLENT',
    seAvailablePower: 20.4,
    mvlSeDistance: 'Inside',
    usableSurface: 8.50,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 2000,
    pvPower: 4.00,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Under Negotiation',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 7,
    projectNumber: '025FCAT25',
    province: 'Barcelona',
    municipality: 'La llacuna',
    closestSe: 'ANOIA',
    seAvailablePower: 21.4,
    mvlSeDistance: 0,
    usableSurface: 12.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 4.00,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Under Negotiation',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 8,
    projectNumber: '031FCAT25',
    province: 'Barcelona',
    municipality: 'Avinyonet del Penedés',
    closestSe: 'MOJA',
    seAvailablePower: 93.7,
    mvlSeDistance: 50,
    usableSurface: 8.90,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 4.00,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Under Negotiation',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 9,
    projectNumber: '032FCAT25',
    province: 'Barcelona',
    municipality: 'Torrella del Foix',
    closestSe: 'MOJA',
    seAvailablePower: 93.7,
    mvlSeDistance: 50,
    usableSurface: 8.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 4.00,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Under Negotiation',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 10,
    projectNumber: '037FCAT25',
    province: 'Barcelona',
    municipality: 'San frutuos del Bages',
    closestSe: 'MANRESA',
    seAvailablePower: 41.7,
    mvlSeDistance: 2.4,
    usableSurface: 8.00,
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 4.00,
    bessPower: 8.00,
    peakPower: 'NA',
    accessCapacity: 'NA',
    technology: 'Fija',
    production: 'NA',
    projectStatus: 'Under Negotiation',
    rtbEstimation: 'NA',
    codEstimation: 'NA'
  },
  {
    id: 11,
    projectNumber: '041FCAT25',
    province: 'Girona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    peakPower: 2.06,
    accessCapacity: 1.7,
    technology: 'Fija',
    production: 3329,
    projectStatus: 'Final EA Obtained - In Operation',
    rtbEstimation: '-',
    codEstimation: 'sep-25'
  },
  {
    id: 12,
    projectNumber: '038FCAT25',
    province: 'Lleida',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    peakPower: 3.28,
    accessCapacity: 2.75,
    technology: 'Fija',
    production: 5304,
    projectStatus: 'Provisional EA Obtained',
    rtbEstimation: '-',
    codEstimation: 'nov-25'
  },
  {
    id: 13,
    projectNumber: '046TARA25',
    province: 'Teruel',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    peakPower: 2,
    accessCapacity: 1.6,
    technology: 'Tracker',
    production: 3914,
    projectStatus: 'Construction License Requested',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 14,
    projectNumber: '047TCAT25',
    province: 'Barcelona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    peakPower: 2.2,
    accessCapacity: 1.8,
    technology: 'Tracker',
    production: 3966,
    projectStatus: 'Pending Construction License Request',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 15,
    projectNumber: '050FCAT25',
    province: 'Barcelona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    peakPower: 2.5,
    accessCapacity: 2,
    technology: 'Fija',
    production: 3966,
    projectStatus: 'Construction License Requested',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 16,
    projectNumber: '051FCAT25',
    province: 'Barcelona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    peakPower: 2.4,
    accessCapacity: 2,
    technology: 'Fija',
    production: 3856,
    projectStatus: 'Construction License Obtained',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 17,
    projectNumber: '053TARA25',
    province: 'Zaragoza',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    peakPower: 30,
    accessCapacity: 25,
    technology: 'Tracker',
    production: 58606,
    projectStatus: 'Construction License Obtained',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  },
  {
    id: 18,
    projectNumber: '054FCAT25',
    province: 'Barcelona',
    municipality: 'NA',
    closestSe: 'NA',
    seAvailablePower: 'NA',
    mvlSeDistance: 'NA',
    usableSurface: 'NA',
    sellingPrice: 'NA',
    unitPrice: 'NA',
    rentingPrice: 'NA',
    pvPower: 'NA',
    bessPower: 'NA',
    peakPower: 3.1,
    accessCapacity: 2.75,
    technology: 'Fija',
    production: 4805,
    projectStatus: 'Construction License Obtained',
    rtbEstimation: 'Q4-2025',
    codEstimation: 'Q2-2027'
  }
]
